duckduckgo/duckduckgo-help-pages

index.md
Welcome page is a little bare ... Simple message + search form?
=> Add search form to Welcome page

_docs/desktop/firefox.md, _docs/features/instant-answers-and-other-features.md
Also removed a couple of out-of-date parts.
Fixes #11
=> Fixed links to missing Instant Answers (fixes #11)

_docs/results/duckduckbot.md
Sorry @moollaza - the end of a sentence got chopped off when I pasted my original edits.
=> Add missing text

_docs/add-ons/safari-12.md
=> Update Safari 12 explanation

Gemfile.lock, _layouts/default.html, _sass/_layout.scss
Hopefully this fixes issue #8 
I was looking for something to do while I had lunch. I realize the issue is pretty old and probably pretty low-priority, but since it only took a few seconds I thought I'd take a stab at it anyway.
=> Updated styling to highlight current page in side nav

_docs/desktop/firefox.md, _docs/desktop/microsoft-edge.md
Also updated the Firefox page with clearer add-on description.
=> Added section for MS Edge add-on

_docs/translated/ads-by-microsoft-on-duckduckgo-private-search-pl_PL.md
Minor updates to the Polish translation.
Corresponding Asana task: https://app.asana.com/0/0/1177947934709328/f
=> Update Polish translation for Ads by Microsoft

_docs/privacy/atb.md
Asana: 
- https://app.asana.com/0/38424471409662/1188711086955269/f
- https://app.asana.com/0/11984721910118/1189116311223401/f
=> Clarify our use of local storage in atb docs

_docs/privacy/content-security-policy-reports.md
As discussed in: 
* https://app.asana.com/0/38424471409662/1191959252625330/f
=> Add new page explaining CSP reports

_docs/privacy/content-security-policy-reports.md
As suggested by @jkv on:
https://app.asana.com/0/481882893211075/1192930554572093/f
=> Update CSP reports URL

_docs/privacy/content-security-policy-reports.md
As discussed on Asana: https://app.asana.com/0/38424471409662/1198559258874902/f
=> Add additional CSP reports URL to the CSP help page

_docs/company/contact-us.md
Updated for more clarity on data processing issues.
=> Updated contact addresses

_docs/results/duckduckbot.md
=> Added new IP address

_layouts/default.html
Adds a link to the commit history on GitHub for each help page.
=> Add created/modified dates to each help page

_docs/results/translation.md
This adds some clarifying text to the translations page, as prescribed here: https://app.asana.com/0/0/1200312437426354/1200550476933118/f
=> Adds clarifying language to translations page.

_docs/privacy/anonymous-localized-results.md
=> Update anonymous-localized-results.md 

_docs/features/finance.md
Adds a new page with the information we're required to provide about stocks data (and, in the not too distant future, for other securities)
Copywriting review: https://app.asana.com/0/38424471409662/1200544187895841/f (approved)
Legal review: https://app.asana.com/0/0/1200544073471550/f (approved)
=> Help page for financial information

_docs/privacy/no-tracking.md
=> update v2 to v3 onion address and replace the term hidden service with onion service

_docs/company/contact-us.md
For IT Governance Europe Limited
=> Update GDPR Address

_docs/privacy/privacy-labels.md
As determined in https://app.asana.com/0/38424471409662/1201803241107388/f
This has been through copy, legal, and privacy review.
Further background information here: https://app.asana.com/0/0/1200811634193214/f
=> Update privacy-labels.md to add information about data collected by apple

_docs/features/finance.md
As discussed on Asana: https://app.asana.com/0/38424471409662/1202561403368919/f
=> Attribute indices data to Refinitiv

_docs/company/ads-by-microsoft-on-duckduckgo-private-search.md
Per https://app.asana.com/0/0/1202636749806014/f
=> Adds authorship note

_docs/features/maps.md, _docs/privacy/privacy-labels.md
Missed these in the previous PR.
=> Fixes broken images with absolute paths.

_docs/privacy/web-tracking-protections.md
Asana:
- https://app.asana.com/0/0/1202728706204891/f
- https://app.asana.com/0/0/1202728706204890/f
Self-merging because it's only a content update.
=> Updates to Surrogates section of Web Tracking Protection page.

_docs/translated/ads-by-microsoft-on-duckduckgo-private-search-is_IS.md
=> Add translated ad authorship note in Icelandic

_docs/privacy/web-tracking-protections.md
Asana: 
- https://app.asana.com/0/1116104605880867/1202945471385207/f (main task)
- https://app.asana.com/0/0/1202945509430933/f (this PR)
ETA: I didn't touch the last line (at least in the 1st commit), so not sure why it's coming up as a diff 🤷‍♀️
=> Update CNAME Cloaking Protection for Android and Fingerprinting Protection for Mac

_docs/features/finance.md
As discussed on Asana:
* https://app.asana.com/0/1116104605880867/1203026015312745/f
=> Update Finance Data help page to include indices disclaimer

_docs/features/bangs.md, _docs/features/instant-answers-and-other-features.md
Update and removes outdated Bangs page URLs.
=> Update Bangs help page URLs

_docs/privacy/web-tracking-protections.md
- Android CPM
- Android fingerprinting
- Android expire 1st party cookies 
- MacOS referrer trimming
- iOS fingerprinting protection completed
- Google sign-in pop-up protection
- CPM cosmetic hiding
- link fixes
Asana tasks:
- https://app.asana.com/0/1116104605880867/1203215173771511/f ➡️ https://app.asana.com/0/0/1203215076181351/f
- https://app.asana.com/0/1116104605880867/1203608279632011/f ➡️ https://app.asana.com/0/0/1203664344672771/f
- https://app.asana.com/0/1202899525821663/1203763198439327/f ➡️  https://app.asana.com/0/0/1203763202762787/f
=> Update web tracking protections

_docs/company/advertise-on-duckduckgo-search.md, _docs/company/advertising-and-affiliates.md
- Update copy on existing "Advertising and Affiliates" page
- Create new "Advertise on DuckDuckGo Search" page
=> Update Advertising Help Pages

_docs/company/advertise-on-duckduckgo-search.md, _docs/settings/params.md
- Remove mentions of `%23` in color-related settings -- its no longer used.
=> Params page update

_docs/company/advertising-and-affiliates.md, _layouts/default.html, scripts/pixels.js
This PR adds engagement pixels for link click and page load events
=> Add link click and page load pixels

_layouts/default.html
close #165 
_layouts/default.html
=> Auto update copyright year

_docs/get-duckduckgo/get-duckduckgo-browser-on-mac.md
Added bullet point about DuckDuckGo Mac App Store version and local files
=> Copy update for DuckDuckGo Mac Page

_docs/get-duckduckgo/get-duckduckgo-browser-on-mac.md
Adjust Mac App Store Version Limitations to be more apparent
re: https://app.asana.com/0/0/1205374926486163/f
=> Add Mac App store version limitations

_docs/get-duckduckgo/get-duckduckgo-browser-on-mac.md
Asana: https://app.asana.com/0/0/1205206500196561/f
Update the minimum macOS requirement from 10.15 or later to 11.4 or later
=> Update macOS minimum requirement

_docs/company/ads-by-tripadvisor-on-duckduckgo-private-search.md
Asana: https://app.asana.com/0/0/1206332570057361/f
Adding help page for tripadvisor ads.
=> Add tripadvisor ads pages

_docs/r-legal/platform-to-business-regulation.md
Updates outdated Bing link on `/r-legal/platform-to-business-regulation/`
=> Updates Bing link in Platform to Business Regulation page

_docs/results/duckduckbot.md
Trivial change, need to add the IP of the 2x new staging proxy servers.
=> Add IPs to duckduckbot.md

_docs/open-source/opensource-overview.md, _docs/privacy/web-tracking-protections.md
**Asana:** 
- https://app.asana.com/0/1116104605880867/1204569403983986/f
- https://app.asana.com/0/1202899525821663/1204622411672204/f
Now that the macOS browser repository has been made public, we can add links and update our open source list 🎉
=> Update to add links to mac browser repo

_docs/sync-and-backup/password-manager-security.md
**Asana task:** https://app.asana.com/0/38424471409662/1207977161664821/f
Creates a help page to inform users about passwordmanager security.
=> Add password manager security page

_includes/data-brokers.md
Updates the broker list for Personal Information Removal with the latest supported brokers.
_(This PR was created automatically, triggered by the merging of [this PR]())_
=> Personal Information Removal: Update Supported Broker List

_docs/duck-player/duck-player.index.md
=> add mobile support info to duck player page espÑol

_docs/aichat/recent-chats.md
Adding a page about the recent chats feature of AI chat, addressing their privacy.
=> Add Recent Chats Page

_docs/privacy-pro/getting-started.md, _docs/privacy-pro/payments.md
replaced Apple ID references with Apple Account
=> replaced Apple ID references with Apple Account
